### ISSUE TITLE
Need NeoLang Username (Important)

### ISSUE THREAD

**Issue by emma-eva** [neolang/neopy#6]
You are not continuing this project from a long time.

I made my new programming language and named it `NeoLang`. Its not possible to change this neolang name from my codes (too many codes and alghrithms).

Actually i need this github username `NeoLang`. Let me publish my codes to make it opensource.

You can help me too much and i will be very happy. I cant contact with you directly bcz cant see any contact details.

I am waiting for your reply. If you want to give me username then please give me permission.

Thank you so much :)

**Comment by creikey** [comment]
> You are not continuing this project from a long time.
> 
> I made my new programming language and named it `NeoLang`. Its not possible to change this neolang name from my codes (too many codes and alghrithms).
> 
> Actually i need this github username `NeoLang`. Let me publish my codes to make it opensource.
> 
> You can help me too much and i will be very happy. I cant contact with you directly bcz cant see any contact details.
> 
> I am waiting for your reply. If you want to give me username then please give me permission on this mail: [neolangosc@gmail.com](mailto:neolangosc@gmail.com)
> 
> Thank you so much :)

As you can see from the commit history, this project is in active revision. The neolang brand is worth its weight in gold. I'll change the product name to Neolang2 if there can be some form of compensation for the lost work in building the brand.

Thanks

**Comment by emma-eva** [comment]
> 

so whats your decission?

**Comment by creikey** [comment]
> > 
> 
> so whats your decission?

I have renamed the project to Neolang 2 as it represents the sequel in code quality and all other important metrics. You are free to use the neolang name now, as it's no longer relevant

**Comment by emma-eva** [comment]
> > > 
> > 
> > 
> > so whats your decission?
> 
> I have renamed the project to Neolang 2 as it represents the sequel in code quality and all other important metrics. You are free to use the neolang name now, as it's no longer relevant

Love you too much sir, i am very happy. Thank you so much
